// Code generated by protoc-gen-go.
// source: msg.proto
// DO NOT EDIT!

/*
Package hello is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	ImgUrl
	User
*/
package hello

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ImgUrl struct {
	Url              *string `protobuf:"bytes,1,req,name=url" json:"url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ImgUrl) Reset()         { *m = ImgUrl{} }
func (m *ImgUrl) String() string { return proto.CompactTextString(m) }
func (*ImgUrl) ProtoMessage()    {}

func (m *ImgUrl) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

type User struct {
	Uid              *int32    `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Uname            *string   `protobuf:"bytes,2,opt,name=uname" json:"uname,omitempty"`
	Imgurl           []*ImgUrl `protobuf:"bytes,3,rep,name=imgurl" json:"imgurl,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}

func (m *User) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *User) GetUname() string {
	if m != nil && m.Uname != nil {
		return *m.Uname
	}
	return ""
}

func (m *User) GetImgurl() []*ImgUrl {
	if m != nil {
		return m.Imgurl
	}
	return nil
}

func init() {
}
